Repository pfe-dev201/pharma-frontend, pull requests merged in 2023-06, with the labels that each got.

#10 [PHARMA-36] Back-end Login
  src/components/loginPage/form.jsx
  src/components/sideBar/sideBar.jsx
  src/views/login/loginView.jsx
Labels: enhancement

#13 [PHARMA-37] View Rapport
  package-lock.json
  package.json
  src/components/formFilterRapport/formFilterRapport.css
  src/components/formFilterRapport/formFilterRapport.jsx
  src/components/sideBar/sideBar.jsx
  src/index.js
  src/views/pharma/content/rapport/rapport.css
  src/views/pharma/content/rapport/rapport.jsx
Labels: enhancement

#15 [PHARMA-37-Bug] View Rapport bug
  package-lock.json
  package.json
  src/components/formFilterRapport/formFilterRapport.jsx
  src/index.js
  src/views/pharma/content/rapport/rapport.jsx
Labels: bug

#16 [PHARMA-39] Authorization
  package-lock.json
  package.json
  src/components/checkLogin.jsx
  src/components/sideBar/sideBar.jsx
  src/index.js
  src/store/store.js
  src/views/pharma/content/rapport/rapport.css
Labels: enhancement

#17 [PHARMA-9] StockView
  src/assets/icons/filter.svg
  src/assets/icons/printer.svg
  src/components/formAjouterMedicament/formAjouterMedicament.jsx
  src/components/formConfigurationStock/formConfigurationStock.jsx
  src/components/formConfigurationStock/formConfigurationStockStyle.css
  src/components/formFiltrer/formFiltrer.jsx
  src/components/formTrier/formTrier.jsx
  src/components/imprimer/imprimer.css
  src/components/imprimer/imprimer.jsx
  src/components/pagination/paginationStyle.css
  src/components/tableau/tableau.css
  src/components/tableau/tableau.jsx
  src/index.js
  src/views/pharma/content/entrees/entreesView.jsx
  src/views/pharma/content/rapportView.jsx
  src/views/pharma/content/reglagesView.jsx
  src/views/pharma/content/stock/stockStyle.css
  src/views/pharma/content/stock/stockView.jsx
Labels: enhancement

#18 [PHARMA-7] PDF generation
  package-lock.json
  package.json
  src/assets/icons/revenir.svg
  src/components/formAjouterUser/formAjouterUser.jsx
  src/components/imprimer/imprimer.jsx
  src/components/revenir/revenir.css
  src/components/revenir/revenir.jsx
  src/views/pharma/content/pdfGenerator.jsx
  src/views/pharma/content/stock/stockStyle.css
  src/views/pharma/content/stock/stockView.jsx
Labels: enhancement

#20 [PHARMA-40] responsive
  package-lock.json
  package.json
  src/components/avatar/avatarStyle.css
  src/components/customAlert/customAlertStyle.css
  src/components/filtrer/filtrer.css
  src/components/formAjouterMedicament/formAjouterMedicament.jsx
  src/components/formAjouterMedicament/formAjouterMedicamentStyle.css
  src/components/imprimer/imprimer.css
  src/components/pagination/paginationStyle.css
  src/components/revenir/revenir.css
  src/components/sideBar/sideBar.css
  src/components/sideBar/sideBar.jsx
  src/components/tableau/tableau.css
  src/components/trier/trier.css
  src/views/login/loginView.css
  src/views/pharma/content/entrees/entreesStyle.css
  src/views/pharma/content/profile/profileStyle.css
  src/views/pharma/content/profile/profileView.jsx
  src/views/pharma/content/reglages/reglagesStyle.css
  src/views/pharma/content/reglages/reglagesView.jsx
  src/views/pharma/content/stock/stockStyle.css
  src/views/pharma/content/welcome/welcomeStyle.css
  src/views/pharma/pharmaStyle.css
  src/views/pharma/pharmaView.jsx
Labels: enhancement

#21 [PHARMA-38] Backend rapport
  src/components/formFilterRapport/formFilterRapport.jsx
  src/views/pharma/content/rapport/rapport.jsx
Labels: enhancement

#22 [PHARMA-38-UPDATE] Backend rapport
  src/components/sideBar/sideBar.jsx
  src/views/pharma/content/rapport/rapport.jsx
Labels: bug, enhancement

#23 [PHARMA-42] responsive rapport
  src/views/pharma/content/profile/profileStyle.css
  src/views/pharma/content/rapport/rapport.css
  src/views/pharma/content/rapport/rapport.jsx
Labels: enhancement

#24 [PHARMA-38-BUG] Backend rapport
  src/views/pharma/content/rapport/rapport.jsx
Labels: bug
